### ISSUE TITLE
show VCN & VCN Compartment instead of just VCN-OCID in the SL & NSG sheets

### ISSUE THREAD

**Issue by Mayur-dba** [KsiriCreations/oci-auditing#7]
Kindly add VCN name & Compartment name to the security list page in the reports. 
and remove VCN OCID, as it can be obtained from VCN tab itself.

This would be helpful to find out the VCN's & compartments instead of navigating to the VCN page and searching for the VCN's with OCIDs.

Additional similar kind of Requests from @erankiraghavendra for NSG

_Restructure formats:_
**SL**
VCN . Compartment . Tenancy | SL Name | SL OCID | Created Time
-- | -- | -- | -- 

**NSG**, 1st table
VCN . Compartment . Tenancy | NSG Name | NSG OCID | NSG Comp | Created Time
-- | -- | -- | -- | -- 

**NSG - Security Rules**, 2nd table
replace NSG OCID with NSG name

**NSG - VNICs**, 3rd table
replace NSG OCID with NSG name

**Comment by kk-hiraskar** [comment]
enhancements #5 & #7, completed, and released in
https://github.com/KsiriCreations/oci-auditing/releases/tag/3.6.8

**Comment by kk-hiraskar** [comment]
found an rare issue in 3.6.8
issue description:
* from stack creations, while creating network components
* if Security-List (SL) got created under a VCN [ocid1.vcn.oc1.iad.aaa111...]
* and if in final save of VCN fails or interrupted, then SL is getting saved with this linked VCN OCID, which never got successfully created [or might be created & destroyed in process]
* **so to conclude these SL exists with an non existing VCN OCID** 

as per this enhancement requests, a **non existing** linked VCN name & it's compartment cannot be displayed.
so for these Orphan SLs, in ver3.6.9 just VCN OCID itself will be shown instead of it's name/compartment.

**Comment by kk-hiraskar** [comment]
ver 3.6.9 will not be released, as showing non-existing VCN OCID can confuse user, and can think tool may be showing wrong or garbage id.

**so just an hyphen (-) symbol will be shown in place of parent VCN details for these kind of any child network components (SL/NSG)**

**Comment by kk-hiraskar** [comment]
reopened fixes, done in v3.6.10, will be packaged & released later.

**Comment by kk-hiraskar** [comment]
these additional fixes are released in ver 3.6.11, for rare issues of orphan SecurityLists to its failed parent VCN which found after #7 implementations.

These kind of orphan SLs should not be allowed by OCI, however OCI Audit tool is updated to also handle these scenarios.
